### ISSUE TITLE
Laybuy Info may not be following the Mandatories on your site from the 2019 Laybuy Launch Guide

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Laybuy/Magento-2-Latest#10]
Looking at the LayBuy launch guide pdf the Popup details and wording elsewhere are different.
There is no Pay By Laybuy button on checkout etc...

Do LayBuy's mandatory requirements have to match closer than this? (It is just a guide?)

I ask because it would be a shame to have LayBuy restricted at some point in the future should the Official Magento 2 module not meet the requirements, and I think it is a positive for the branding/marketing aspect to follow the guide closer.

I'm emailing Scott, onboarding@laybuy.com for more info linking them this issue.

See page 8-9 "Mandatories on your site."

- [] *It's important to show how Laybuy works as simply as possible to customers. Using simple icons and minimal text to explain, and lots of white space to keep things simple.
- [] *The current popup does not look like their popup, branding for Laybuy including that in the popup might have to be consistent across implementations updated regarding the 2019 Guide?
Including the symbols/icons.

Screenshots;

Laybuy Launch Guide Pages 7,8,9.
![image](https://user-images.githubusercontent.com/1968109/69292136-2d0b3f80-0c6a-11ea-8431-2011523409ad.png)
![image](https://user-images.githubusercontent.com/1968109/69292146-35fc1100-0c6a-11ea-8861-ddeb398fc6e2.png)
![image](https://user-images.githubusercontent.com/1968109/69292200-604dce80-0c6a-11ea-8088-9261f803e4ce.png)

Footer logo?
![image](https://user-images.githubusercontent.com/1968109/69292243-7a87ac80-0c6a-11ea-94c0-1fc8e0bbf4f1.png)

Presently the Magento 2 plugin popup shows as this.
![image](https://user-images.githubusercontent.com/1968109/69291413-0d731780-0c68-11ea-82a4-75851c9e6a12.png)

I've seen another website implement it differently like this. (not Magento 2 / affiliated)
![image](https://user-images.githubusercontent.com/1968109/69291432-1b289d00-0c68-11ea-9876-ecda9620b193.png)

And an older Magento 2 site using the previous Laybuy extension looked like this.
![image](https://user-images.githubusercontent.com/1968109/69291998-b8d09c00-0c69-11ea-9061-2914ecb4ec6f.png)
Clicking What's this simply redirects to https://www.laybuy.com/what-is-laybuy

![image](https://user-images.githubusercontent.com/1968109/69293369-8c1e8380-0c6d-11ea-8c3b-d74e2b59aa34.png)

If I recall I had to add the Pay By laybuy image into that button as well, as it was not there.

Magento 2 does not have the Pay by Laybuy button on checkout.

Payment Method when closed.
![image](https://user-images.githubusercontent.com/1968109/69292860-0a7a2600-0c6c-11ea-956f-bf3cf55cbc3c.png)

Payment Method when open.
![image](https://user-images.githubusercontent.com/1968109/69292873-136af780-0c6c-11ea-91fc-e5cd37ee1580.png)

### Proposals
- [] Move the Laybuy logo (slightly smaller?) before the payment method title, so its shown when closed, hide the method title as the image says it, set Alt tag of img correctly to read Pay by LayBuy.
- [] Modify the Continue to Laybuy button to a Pay by Laybuy image button.
![image](https://user-images.githubusercontent.com/1968109/69292949-42816900-0c6c-11ea-95a8-3ff65d5a9bc5.png)

E.g.
![image](https://user-images.githubusercontent.com/1968109/69293787-d18f8080-0c6e-11ea-872f-b97676e6a7b2.png)
Resized down of course.

Source the logos from the official dropbox/download of course.

Similar, Driving Sales might be able to be implemented in an easy way into this module although this section is not mandatory and probably varies depending per each store design and modules/configuration...

### Marketing/Branding
- [] Header Banner (Implementation of this could vary depending on per site header/module implementations. See pages 11-12
- [] Footer logo, 100px x 50px is the minimum size.
- [] Content Banner, could be a block we can add anywhere to have consistent wording and logo across all installations.
- [] Launch email ability to send to existing customers with the appropriate pre-formatted graphics/wording.

### Nice to haves:
- [] Support for Light/Dark logos depending on your theme it may look better.

Kind regards,
Liam

**Comment by LiamKarlMitchell** [comment]
Told we can use https://popup.laybuy.com

Maybe something like this.

```js
    require([
        'jquery',
        'popupWindow'
    ], function ($) {
        'use strict';

        $(".laybuy-modal-popup-trigger").popupWindow({
              "windowURL": "https://popup.laybuy.com/",
              "windowName": "How Laybuy works.",
              "width": 600,
              "height": 500,
              "left": 0,
              "top": 0,
              "resizable": 1,
              "scrollbars": 1
        });
    });
```

Or maybe this inside the modal shown on the screen, if there is concern about opening a new popup window.
```html
    <div id="laybuy-modal-popup">
        <div class="laybuy-content-wrapper">
            <iframe src="https://popup.laybuy.com/" width="100%" height="520" frameborder="0"></iframe>
        </div>
    </div>
```

**Comment by LiamKarlMitchell** [comment]
Actually, just noticed there were updates to the module 10 days ago that modify the popup I'll update and re-check :)

**Comment by nikolai-overdose** [comment]
Closed due to age and since updated marketing/branding.
