### ISSUE TITLE
Response.php code in catch undefined variable order.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Laybuy/Magento-2-Latest#12]
1 exception(s):
Exception #0 (Exception): Notice: Undefined variable: order in app/code/Laybuy/Laybuy/Controller/Payment/Response.php on line 176

Should possibly wrap this in an isset.
```php
            if (isset($order)) {
                if (!$order->getId()) {
                    $this->laybuy->laybuyCancel($token);
                }
            }
```

There was an exception elsewhere, before $order is set.

At $quote->collectTotals();

On refresh of home page I did see notices such as.
Laybuy: There was an error confirming your order
The shipping method is missing. Select the shipping method and try again.

Add this to the catch to see error in log.
```php
$this->logger->debug(['process error ' => $e->getMessage()]);
```

Investigating, we do have some conditional shipping methods based on address area and items in cart, maybe they need to always be enabled when handling the LayBuy response?

I think the shipping method is mandatory to set before collectTotals can be called, I chose one on checkout but it conditionally disappears based on the fields and/or cart items at checkout.

It used to work before I updated.

**Comment by drevidchuck** [comment]
Hello @LiamKarlMitchell 
Thanks for reporting this issue, this is now fixed in https://github.com/Laybuy/Magento-2-Latest/commit/654d060cdbdda2eaa1738a02d90b6a3c5ae67b43
