### ISSUE TITLE
Does not use special price when calculating.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Laybuy/Magento-2-Latest#15]
![image](https://user-images.githubusercontent.com/1968109/69684220-b31cff80-111c-11ea-8a85-6384ddcc9e45.png)

![image](https://user-images.githubusercontent.com/1968109/69684313-1eff6800-111d-11ea-8c3d-b0c357643012.png)

Should take special price into account.
Could have sworn this used to just be phtml/block but there is JavaScript in there now.

```js
var price = Math.min.apply(null, $('.price-wrapper',this).map(function(){
  return $(this).data('price-amount')
}).get());
```

Would something like that work?
Or should it be more explicit?

Cart seems fine as it takes from Total just Product and Category have the issue.

**Comment by drevidchuck** [comment]
Hello @LiamKarlMitchell 
Thanks for reporting this issue
These is now fixed in https://github.com/Laybuy/Magento-2-Latest/commit/15a9a5e16810b2cb8ce0820d0a6abdb22c61797f
