### ISSUE TITLE
Currency Symbol not shown on Category laybuy block.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Laybuy/Magento-2-Latest#16]
Which is odd because it uses utils.formatPrice

![image](https://user-images.githubusercontent.com/1968109/69685718-4442a500-1122-11ea-9a29-9eccfa5836fa.png)

**Comment by drevidchuck** [comment]
Hello @LiamKarlMitchell 
Thank you for reporting this issue
We've fixed it in https://github.com/Laybuy/Magento-2-Latest/commit/59d77531195e09d63d5b6a3f23d39ba063e47e0e
