### ISSUE TITLE
Guest user laybuy checkout redirects to cart

### ISSUE THREAD

**Issue by Ramya-M-R** [Laybuy/Magento-2-Latest#18]
I have tried to place order by using guest checkout via laybuy payment method.

If I'm a guest user, I have tried to place an order by clicking laybuy button on payment method. But it redirects to cart page. This issue happened randomly.

**Comment by jackie-od** [comment]
Hi Ramya-M-R,

Maybe you could attach the laybuy.log for us to be able to see if there are any problems being encountered. We are trying this on a Fresh Magento instance and we have not encountered this issue.

Thanks!

**Comment by nikolai-overdose** [comment]
Closed - cannot reproduce.
