### ISSUE TITLE
Issue with button redirect to cart page

### ISSUE THREAD

**Issue by nehatomarhestabit** [Laybuy/Magento-2-Latest#33]
I have added this module in my site.. 
Link : http://staging.hlfashions.co.uk 
on checkout page when i click proceed with Laybuy it redirect me to Cart page.. I am sharing laybuy.log with you plz help me this asap..

laybuy.log File : 

[2021-10-19 07:38:03] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Controller\\Payment\\Process::execute' => 'start',
) [] []
[2021-10-19 07:38:04] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Model\\Laybuy::createLaybuyOrder CREATED ORDER' => 
  (object) array(
     'amount' => '19.20',
     'currency' => 'GBP',
     'returnUrl' => 'http://staging.hlfashions.co.uk/laybuy/payment/response/',
     'merchantReference' => '000000123',
     'customer' => 
    (object) array(
       'firstName' => 'Test',
       'lastName' => 'Test',
       'email' => 'ritypo@zetmail.com',
       'phone' => '0987654321',
    ),
     'items' => 
    array (
      0 => 
      (object) array(
         'id' => 1,
         'description' => '000000123',
         'quantity' => 1,
         'price' => '19.20',
      ),
    ),
  ),
) [] []
[2021-10-19 07:38:05] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Gateway\\Http\\LaybuyClient::getRedirectUrlAndToken' => 
  (object) array(
     'result' => 'ERROR',
     'error' => 'Authentication Failed',
  ),
) [] []
[2021-10-19 07:38:05] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Controller\\Payment\\Process::execute  LAYBUY STATUS ' => 'FAILED',
) [] []
[2021-10-19 07:40:34] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Controller\\Payment\\Process::execute' => 'start',
) [] []
[2021-10-19 07:40:35] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Model\\Laybuy::createLaybuyOrder CREATED ORDER' => 
  (object) array(
     'amount' => '19.20',
     'currency' => 'GBP',
     'returnUrl' => 'http://staging.hlfashions.co.uk/laybuy/payment/response/',
     'merchantReference' => '000000123',
     'customer' => 
    (object) array(
       'firstName' => 'Test',
       'lastName' => 'Test',
       'email' => 'ritypo@zetmail.com',
       'phone' => '0987654321',
    ),
     'items' => 
    array (
      0 => 
      (object) array(
         'id' => 1,
         'description' => '000000123',
         'quantity' => 1,
         'price' => '19.20',
      ),
    ),
  ),
) [] []
[2021-10-19 07:40:36] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Gateway\\Http\\LaybuyClient::getRedirectUrlAndToken' => 
  (object) array(
     'result' => 'ERROR',
     'error' => 'Authentication Failed',
  ),
) [] []
[2021-10-19 07:40:36] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Controller\\Payment\\Process::execute  LAYBUY STATUS ' => 'FAILED',
) [] []
[2021-10-19 07:48:28] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Controller\\Payment\\Process::execute' => 'start',
) [] []
[2021-10-19 07:48:30] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Model\\Laybuy::createLaybuyOrder CREATED ORDER' => 
  (object) array(
     'amount' => '19.20',
     'currency' => 'GBP',
     'returnUrl' => 'http://staging.hlfashions.co.uk/laybuy/payment/response/',
     'merchantReference' => '000000123',
     'customer' => 
    (object) array(
       'firstName' => 'Test',
       'lastName' => 'Test',
       'email' => 'ritypo@zetmail.com',
       'phone' => '0987654321',
    ),
     'items' => 
    array (
      0 => 
      (object) array(
         'id' => 1,
         'description' => '000000123',
         'quantity' => 1,
         'price' => '19.20',
      ),
    ),
  ),
) [] []
[2021-10-19 07:48:31] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Gateway\\Http\\LaybuyClient::getRedirectUrlAndToken' => 
  (object) array(
     'result' => 'ERROR',
     'error' => 'Authentication Failed',
  ),
) [] []

Thanks

**Comment by insaurabh** [comment]
Any update on this?

Or any suggestion to debug more in the plugin.

**Comment by nikolai-overdose** [comment]
Incorrect API credentials.
