### ISSUE TITLE
Couldn't initialize Laybuy payment method

### ISSUE THREAD

**Issue by iliyasmsc** [Laybuy/Magento-2-Latest#5]
I have installed Module on Magento2.1.17 its display on payment method list but when i place order it will redirect to me on checkout cart page with error message "Couldn't initialize Laybuy payment method." can any one help me solve this out.

This is laybuy log:
[2019-07-14 09:31:43] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Controller\\Payment\\Process::execute' => 'start',
) {"is_exception":false} []
[2019-07-14 09:31:43] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Model\\Laybuy::createLaybuyOrder CREATED ORDER' => 
  stdClass::__set_state(array(
     'amount' => '384.99',
     'currency' => 'GBP',
     'returnUrl' => 'https://www.xyz.com/laybuy/payment/response/',
     'merchantReference' => '000000376',
     'customer' => 
    stdClass::__set_state(array(
       'firstName' => 'abdul',
       'lastName' => 'test',
       'email' => 'abdul@gmail.com',
       'phone' => '00 000 000',
    )),
     'items' => 
    array (
      0 => 
      stdClass::__set_state(array(
         'id' => 1,
         'description' => '000000376',
         'quantity' => 1,
         'price' => '384.99',
      )),
    ),
  )),
) {"is_exception":false} []
[2019-07-14 09:31:43] Laybuy Logger.DEBUG: array (
  'Laybuy\\Laybuy\\Controller\\Payment\\Process::execute  LAYBUY STATUS ' => 'FAILED',
) {"is_exception":false} []

**Comment by drevidchuck** [comment]
Hello @iliyasmsc 
Looking at your log, I can see that payment method fails on sending order to Laybuy, and rest client couldn't be initialised. To confirm that, could you also check exception.log?
