### ISSUE TITLE
Installment prices on simple products with Customizable Options are calculated incorrectly

### ISSUE THREAD

**Issue by stewnight** [Laybuy/Magento-2-Latest#6]
Using Magento 2.3.2
With this extension installed, any of my products with Customizable Options calculate the installments at $0.17 each, despite the price originally showing correctly.

Customizable Options have the value of + $0.00 - However when they are set to 100%, selecting an option changes the installments from $0.17 to $0.33.

During page load the correct installments show, but then they're overwritten before the user can interact with the page.

**Comment by stewnight** [comment]
I have further detail to add.
It only applies for Products that RRP is $1,000 or greater and have Customizable Options
$999 and less will calculate the instalments correctly for products with customizable options.
Products $1,000 or greater that do not have Customizable Options calculate the instalments correctly.

**Comment by drevidchuck** [comment]
Hello @dooB1EE 
Thank you for you feedback, I have tested it, and yes you're correct, installments display logic didn't work correctly with how magento formatted price output using ',' symbol. Fix for that is in the latest commit https://github.com/Laybuy/Magento-2-Latest/commit/ca6de4b7862fe7a645f8c02d0ecdc7b28aa05b2a
This should resolve your issue, thanks again for detailed issue description
