### ISSUE TITLE
Magento 2 Invoice email not sent to notify customer?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Laybuy/Magento-2-Latest#7]
This could be by design however, as LayBuy would send their own?
But Magento 2 does have a built in Invoice email that should be sent to the Customer and any Bcc'd emails (e.g. sales staff that need to be notified of the paid invoice/order to process it).

https://github.com/Laybuy/Magento-2-Latest/blob/master/Model/Laybuy.php#L409

My thinking is that Laybuy.php createInvoiceAndUpdateOrder should use an invoiceSender 
https://github.com/pepe1518/magento2/blob/master/vendor/magento/module-sales/Model/Order/Email/Sender/InvoiceSender.php

https://www.rakeshjesadiya.com/how-to-create-invoice-programmatically-in-magento-2/

\Magento\Sales\Model\Order\Email\Sender\InvoiceSender $invoiceSender,
$this->invoiceSender->send($invoice);

**Comment by LiamKarlMitchell** [comment]
Confirmed using Sandbox API key.

This module is not sending the Magento 2 Invoice Email automatically.
https://github.com/magento/magento2/issues/13466

**Comment by drevidchuck** [comment]
Hello @LiamKarlMitchell 
We have added functionality to send invoices upon creation for orders paid by Laybuy https://github.com/Laybuy/Magento-2-Latest/commit/c58bd29310df019104826f793f0bbd80a3548e16
It's disabled by default, but you can enable it in payment module configuration

**Comment by LiamKarlMitchell** [comment]
Brillant thanks @drevidchuck :)

**Comment by LiamTrioTech** [comment]
Just noticed, invoice number does not appear to be showing on the email.
